# Generated by Django 5.0.4 on 2024-04-14 15:55

import ckeditor.fields
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(default=0, verbose_name='排序位置')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='分类名称')),
                ('remark', ckeditor.fields.RichTextField(blank=True, default='', max_length=255, null=True, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'db_table': 'onlearn_course_category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='课程名称')),
                ('orders', models.IntegerField(default=0, verbose_name='排序位置')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course_cover', stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=255, null=True, upload_to='course/cover', variations={'thumb_1080x608': (1080, 608), 'thumb_108x61': (108, 61, True), 'thumb_540x304': (540, 304)}, verbose_name='封面图片')),
                ('course_video', models.FileField(blank=True, max_length=255, null=True, upload_to='course/video', verbose_name='封面视频')),
                ('course_type', models.SmallIntegerField(choices=[(0, '免费课程'), (1, '付费课程')], default=0, verbose_name='付费类型')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='详情介绍')),
                ('attachment_path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='课件路径')),
                ('attachment_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='课件链接')),
                ('status', models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=0, verbose_name='课程状态')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='课程原价')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_list', to='course.coursecategory', verbose_name='学习分类')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
                'db_table': 'onlearn_course_info',
            },
        ),
    ]
