# Generated by Django 5.0.4 on 2024-04-14 16:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='详情介绍'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='remark',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=255, null=True, verbose_name='分类描述'),
        ),
    ]
