# Generated by Django 5.0.4 on 2024-04-19 09:24

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_description_alter_coursecategory_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attachment_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='课件链接'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_list', to='course.coursecategory', verbose_name='课程分类'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_cover',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='course/cover/', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='课程视频'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='详情介绍'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='remark',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='分类描述'),
        ),
    ]
