# Generated by Django 5.0.4 on 2024-04-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chapter_list', to='course.course', verbose_name='课程'),
        ),
    ]
