# Generated by Django 5.0.4 on 2024-04-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_attachment_link_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chapters',
            field=models.JSONField(blank=True, null=True, verbose_name='章节信息'),
        ),
    ]
