# Generated by Django 5.0.4 on 2024-04-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_chapter_course_remove_chapter_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='chapters',
        ),
    ]
