# Generated by Django 5.0.4 on 2024-04-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_chapter_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='attachment_path',
        ),
    ]
