# Generated by Django 5.0.4 on 2024-05-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_attachment_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_selled',
            field=models.BooleanField(default=False, verbose_name='是否已购买'),
        ),
    ]
