# Generated by Django 5.0.4 on 2024-05-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_course_is_selled_selledcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selledcourse',
            options={'verbose_name': '已购课程', 'verbose_name_plural': '已购课程'},
        ),
        migrations.AlterModelTable(
            name='selledcourse',
            table='onlearn_selled_course',
        ),
    ]
