# Generated by Django 5.0.4 on 2024-05-10 14:18

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_selledcourse_options_alter_selledcourse_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='详情介绍'),
        ),
    ]
