# Generated by Django 5.0.4 on 2024-05-15 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='优惠券名称')),
                ('type', models.IntegerField(choices=[(1, '满减券'), (2, '折扣券')], verbose_name='优惠券类型')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠券面值')),
                ('description', models.CharField(max_length=200)),
                ('total', models.IntegerField(blank=True, default=100, verbose_name='发放数量')),
                ('remain', models.IntegerField(blank=True, default=100, verbose_name='剩余数量')),
                ('start_time', models.DateTimeField(verbose_name='启用时间')),
                ('end_time', models.DateTimeField(verbose_name='过期时间')),
                ('condition', models.IntegerField(blank=True, default=0, verbose_name='满足使用优惠券的价格条件')),
                ('per_limit', models.SmallIntegerField(default=1, verbose_name='每人限制领取数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='优惠券用户')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'onlearn_coupon',
            },
        ),
    ]
