# Generated by Django 5.0.4 on 2024-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_chapter_course_remove_chapter_video_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collections',
            field=models.ManyToManyField(blank=True, to='course.course', verbose_name='收藏课程'),
        ),
    ]
