# Generated by Django 5.0.4 on 2024-04-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collections',
        ),
    ]
