# Generated by Django 5.0.4 on 2024-04-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='onlearn_post',
        ),
    ]
