# Generated by Django 5.0.4 on 2024-05-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbs_up',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
