# Generated by Django 5.0.4 on 2024-04-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='courses',
            new_name='course',
        ),
    ]
