# Generated by Django 5.0.4 on 2024-04-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_course_cart_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='number',
        ),
    ]
