# Generated by Django 5.0.4 on 2024-04-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='courses',
        ),
    ]
