# Generated by Django 5.0.4 on 2024-04-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collections',
        ),
    ]
