# Generated by Django 5.0.4 on 2024-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_chapters'),
        ('users', '0004_remove_user_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collector', to='course.course', verbose_name='收藏课程'),
        ),
    ]
